dist: xenial
language: python
python:
  - "3.7"
cache: apt
branches:
  only:
  - master
install:
  - "pip install -r requirements.dev.txt"
script:
  - "cd docs"
  - "sphinx-build --version"
  - "make html"
after_success:
  - echo "https://${GITHUB_TOKEN}:@github.com" > .git/credentials
  - git config credential.helper "store --file=.git/credentials"
  - git clone --quiet --single-branch --branch=gh-pages https://${GITHUB_TOKEN}@github.com/gaulinmp/reslib ../reslib_docs
  - find ../reslib_docs -not -wholename "*.git/*" -type f -delete
  - rsync -rv --exclude=.git ./_build/html/ ../reslib_docs
  - cd ../reslib_docs
  - touch .nojekyll
  - head index.html
  - git add --no-ignore-removal .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to Github Pages"
  - git push origin gh-pages
notifications:
  email:
    on_success: always
    on_failure: always
